version: '3.9'

services:
  api01: &api
    image: yanmiranda/sizebay:latest
    container_name: api01
    hostname: api01
    environment:
      - DB_URL=jdbc:postgresql://db:5432/sizebay
      - DB_USER=sizebay
      - DB_PASSWORD=sizebay
      - JAVA_TOOL_OPTIONS=-Xmx180m -Xms180m -XX:+UseSerialGC
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '180MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '70MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=sizebay
      - POSTGRES_USER=sizebay
      - POSTGRES_DB=sizebay
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '120MB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sizebay -d sizebay"]
      interval: 5s
      timeout: 5s
      retries: 5